### ISSUE TITLE
meta: new release: fancycompleter/pyrepl maintenance

### ISSUE THREAD

**Issue by blueyed** [pdbpp/pdbpp#260]
After antocuni/pdb was rebased onto the proper original history from the Mercurial repo on bitbucket in pdbpp/pdbpp (https://github.com/pdbpp/rebased-pdbpp/pull/8), antocuni/pdb was first moved to pdbpp/old-pdbpp, but then to pdbpp/pdbpp to keep issues and other meta data - but the master branch was changed to use the rebased version.  See https://github.com/pdbpp/rebased-pdbpp/pull/8 for more details.

The plan now is to maintain fancycompleter in the pdbpp org (here), and move pyrepl to the pypy org.

TODO:

- [ ] pyrepl
  - [ ] move https://bitbucket.org/pypy/pyrepl to https://github.com/pypy/pyrepl
    - [x] transfer https://github.com/pdbpp/pyrepl to https://github.com/pypy/pyrepl @antocuni 
    - [ ] clean up master there, maybe start back from original tip, but likely more by amending packaging related things @blueyed 
    - [ ] update README/redirect https://bitbucket.org/pypy/pyrepl
    - [x] setup deployment via Travis tags @antocuni 

- [ ] fancycompleter
  - will live in https://github.com/pdbpp/fancycompleter
  - [ ] update README/redirect https://bitbucket.org/antocuni/fancycompleter/ @antocuni 
  - [ ] setup deployment via Travis tags @antocuni 

- [ ] pdbpp
  - [ ] clean up / revisit dependencies @blueyed - https://github.com/pdbpp/pdbpp/pull/258
  - [ ] Travis: update PyPI deployment config (repo name, credentials?)  @antocuni 

For deployment to PyPI a dedicated PyPI user should be used probably.  @antocuni

**Comment by technillogue** [comment]
Hi, I'm interested in contributing to this, but it's not clear to me what exactly needs to be done. Would opening more specific issues on each repo make sense?

**Comment by blueyed** [comment]
Thanks for your interest in helping out!
A lot of things are about infrastructure, and I probably need to have an IRC session about this with @antocuni again (he is not paying much attention to GitHub notifications, but available e.g. on `#pypy` on Freenode).

The next step would be to get pyrepl into shape I think.
I've done some merging with/from PyPy's version in https://github.com/pypy/pyrepl/pull/2 (but it's a mess IIRC).  The problem there is that things have been done in "pyrepl" itself, while it was already vendored into PyPy (and the other way around).  https://github.com/pypy/pyrepl is meant to become the source of truth, but like stated in the TODO above, its master should maybe also get cleaned up / reset.

**Comment by sodre** [comment]
@blueyed, with fancycompleter, is it the plan to take over the pypi package as well, or are you going to maintain a fork, e.g. pdbpp-fancycompleter?

**Comment by blueyed** [comment]
@sodre that has been moved to https://github.com/pdbpp/fancycompleter already.

**Comment by sodre** [comment]
@blueyed, thanks for the link! Will the `fancycompleter` packages in pypi also come from pdbpp/fancycompleter from now on?

**Comment by blueyed** [comment]
@sodre that's the plan, yes.
